---
title: "Powerlaw Clustering Results"
author: "Niklas Dewally"
date: "23rd May 2023"
output:
  pdf_document: default
  html_document: default
header-includes: | 
  \usepackage{helvet}
  \renewcommand{\familydefault}{\sfdefault}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loaddata,include=FALSE}
library(readr)
data <- read_csv("data.csv", col_types = cols(model = col_factor(levels = c("triangle", 
     "egi")), src = col_factor(levels = c("unclustered", 
     "clustered")), target = col_factor(levels = c("unclustered", 
     "clustered"))))
```


```{r pretty_table, echo=FALSE,message=FALSE}
library(dplyr)
library(knitr)
grouped<- data %>% group_by(src,target,model) %>% 
  summarise(`source-accuracy` = mean(`source-accuracy`),
            `target-accuracy` = mean(`target-accuracy`))
knitr::kable(grouped)
```
* * * 

```{r plot, echo=FALSE,message=FALSE}
library(tidyr)
library(ggplot2)
library(stringr)

plotData <- data %>%
  pivot_longer(cols=c(`source-accuracy`,`target-accuracy`),
               names_to="srctarget",values_to="accuracy") %>%
  
  mutate(`srctarget`=str_replace(`srctarget`,"source-accuracy","source")) %>%
  mutate(`srctarget`=str_replace(`srctarget`,"target-accuracy","target")) %>%    
  unite(`srctarget`,`model`,col=`label`,sep=" ",remove=FALSE) 

p <- ggplot(plotData,aes(x=`accuracy`,y=`label`,colour=`model`)) + 
  geom_boxplot() + 
  facet_grid(rows=vars(`src`),cols=vars(`target`)) +
  ggtitle("Model types by source and target graph type (scale-free).")
p + theme_bw()
```
