---
title: "Clustering Results"
author: "Niklas Dewally"
execute:
  warning: false
params:
  filename: "data.csv"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(dplyr)
library(knitr)
library(tidyr)
library(ggplot2)
library(stringr)
```

```{r include=FALSE}
data <- read_csv(params$filename)
data %>% filter(`graph_type` == "powerlaw")
```

```{r echo=FALSE,message=FALSE}
grouped<- data %>% group_by(src,target,model,`src-size`,`target-size`) %>% 
  summarise(`source-accuracy` = mean(`source-accuracy`),
            `target-accuracy` = mean(`target-accuracy`))

knitr::kable(grouped)
```
* * * 

```{r echo = FALSE, message=FALSE}

boxPlot <- function(df,title="") {
  p <- ggplot(df ,aes(x=`accuracy`,y=`label`,colour=`model`)) + 
       geom_boxplot() + 
       facet_grid(c("src_label","target_label")) +
       ggtitle(title)

  return(p)
}
```


```{r echo=FALSE, message=FALSE}
# tidy graph data for graphing
df <- data %>%
  pivot_longer(cols=c(`source-accuracy`,`target-accuracy`),
               names_to="srctarget",values_to="accuracy") %>%

  mutate(`srctarget`=str_replace(`srctarget`,"source-accuracy","source")) %>%
  mutate(`srctarget`=str_replace(`srctarget`,"target-accuracy","target")) %>%    
  unite(`srctarget`,`model`,col=`label`,sep=" ",remove=FALSE) %>%
  unite(`src`,`src-size`,col=`src_label`,sep=" ",remove=FALSE) %>%
  unite(`target`,`target-size`,col=`target_label`,sep=" ",remove=FALSE) 
```

```{r echo=FALSE, message=FALSE}
boxPlot(filter(df,`srctarget` == "source"))
```


```{r echo=FALSE}
boxPlot(filter(df,`srctarget` == "target"))
```

```{r echo=FALSE}
boxPlot(df)
```

## Is transfer positive or negative?

```{r echo=FALSE}
transfer_df <- grouped %>% mutate(delta = `target-size` - `src-size`)
```

Negative transfer:

```{r echo=FALSE}
knitr::kable(transfer_df %>% filter(`delta` <= 0))
```

Positive transfer:

```{r echo=FALSE}
knitr::kable(transfer_df %>% filter(`delta` > 0))
```
